# Generated by Django 3.0.5 on 2020-09-20 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('categoria_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código de categoria')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('id_jefe', models.IntegerField(verbose_name='Identificación Jefe')),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('parada_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40, unique=True)),
                ('create', models.DateField(auto_now=True, null=True, verbose_name='Fecha creación')),
                ('active', models.BooleanField(default=True, verbose_name='Ficha Técnica Activo')),
                ('sector_asignado', models.CharField(choices=[('TINTAS', 'TINTAS'), ('MONTAJE', 'MONTAJE'), ('DEPÓSITO', 'DEPÓSITO'), ('MANTENIMIENTO', 'MANTENIMIENTO'), ('PROGRAMACIÓN', 'PROGRAMACIÓN'), ('SUPERVICIÓN', 'SUPERVICIÓN'), ('PRODUCCIÓN', 'PRODUCCIÓN'), ('OPERATIVO', 'OPERATIVO'), ('CALIDAD', 'CALIDAD')], max_length=30)),
                ('delete', models.DateField(blank=True, null=True, verbose_name='Fecha baja')),
            ],
            options={
                'db_table': 'parada',
                'ordering': ['parada_id'],
            },
        ),
        migrations.CreateModel(
            name='Operario',
            fields=[
                ('legajo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('create', models.DateField(auto_now=True, db_column='creacion', verbose_name='Fecha creación')),
                ('activo', models.BooleanField(verbose_name='Operario Activo')),
                ('delete', models.DateField(blank=True, null=True, verbose_name='Fecha baja')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicaWebApp.Categoria')),
            ],
            options={
                'db_table': 'operario',
                'ordering': ['legajo'],
            },
        ),
    ]
