# Generated by Django 3.0.5 on 2020-09-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicaWebApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AddField(
            model_name='categoria',
            name='created',
            field=models.DateTimeField(auto_now=True, db_column='creado', verbose_name='Fecha de alta'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_column='modificado', verbose_name='Fecha modificado'),
        ),
    ]
