# Generated by Django 3.0.5 on 2020-09-22 01:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('practicaWebApp', '0002_auto_20200920_0812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cambio_Mecanico',
            fields=[
                ('cambio_id', models.AutoField(primary_key=True, serialize=False)),
                ('create', models.DateTimeField(blank=True, db_column='creacion', default=datetime.datetime.now, null=True, verbose_name='Fecha creación')),
                ('fecha_fin', models.DateTimeField(verbose_name='Fin cambio')),
                ('parada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='practicaWebApp.Parada', verbose_name='Parada')),
            ],
            options={
                'verbose_name': 'Cambio mecánico',
                'verbose_name_plural': 'Cambios Mecánicos',
                'db_table': 'cambio_mecanico',
            },
        ),
        migrations.CreateModel(
            name='Ficha_tecnica',
            fields=[
                ('ficha_tecnica_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Ficha Técnica Id')),
                ('nombre', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True, verbose_name='Ficha Técnica Activo')),
                ('create', models.DateField(auto_now=True, db_column='creacion', null=True, verbose_name='Fecha creación')),
                ('delete', models.DateField(blank=True, null=True, verbose_name='Fecha baja')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ficha Técnica',
                'verbose_name_plural': 'Fichas Técnicas',
                'db_table': 'ficha_tecnica',
                'ordering': ['ficha_tecnica_id'],
            },
        ),
        migrations.CreateModel(
            name='Impresora',
            fields=[
                ('impresora_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('create', models.DateField(auto_now=True, db_column='creacion', verbose_name='Fecha creación')),
                ('activo', models.BooleanField(default=True, verbose_name='Impresora Activa')),
                ('delete', models.DateField(blank=True, null=True, verbose_name='Fecha baja')),
            ],
            options={
                'db_table': 'impresora',
                'ordering': ['impresora_id'],
            },
        ),
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('setup_id', models.AutoField(primary_key=True, serialize=False)),
                ('create', models.DateTimeField(blank=True, db_column='creacion', default=datetime.datetime.now, null=True, verbose_name='Fecha creación')),
                ('fecha_fin', models.DateTimeField(verbose_name='Fin Setup')),
                ('parada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='practicaWebApp.Parada', verbose_name='Parada')),
            ],
            options={
                'verbose_name': 'Setup',
                'verbose_name_plural': 'Setups',
                'db_table': 'setup',
            },
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('produccion_id', models.AutoField(primary_key=True, serialize=False)),
                ('create', models.DateTimeField(blank=True, db_column='creacion', default=datetime.datetime.now, null=True, verbose_name='Fecha de creación')),
                ('fecha_fin', models.DateTimeField(verbose_name='Fin producción')),
                ('parada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='practicaWebApp.Parada', verbose_name='Parada')),
            ],
            options={
                'verbose_name': 'Producción',
                'verbose_name_plural': 'Producciones',
                'db_table': 'produccion',
            },
        ),
        migrations.CreateModel(
            name='Parte_Impresion',
            fields=[
                ('parte_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Orden impresión')),
                ('create', models.DateField(auto_now=True, db_column='creacion', verbose_name='Fecha creación')),
                ('metros_registro', models.IntegerField(verbose_name='Metros registro')),
                ('kg_registro', models.IntegerField(verbose_name='Kg. registro')),
                ('metros', models.IntegerField(verbose_name='Metros producidos')),
                ('kg', models.IntegerField(verbose_name='Kg producidos')),
                ('ayudante1ero', models.ForeignKey(db_column='ayudante1er', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ayudante1er', to='practicaWebApp.Operario', verbose_name='Primer ayudante')),
                ('ayudante2do', models.ForeignKey(db_column='ayudante2do', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ayudante2do', to='practicaWebApp.Operario', verbose_name='Segundo ayudante')),
                ('cambio', models.ManyToManyField(blank=True, db_column='cambio_id', related_name='cambio', to='practicaWebApp.Cambio_Mecanico', verbose_name='Cambio Mecánico')),
                ('ficha_tecnica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicaWebApp.Ficha_tecnica')),
                ('impresora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicaWebApp.Impresora')),
                ('maquinista', models.ForeignKey(db_column='maquinista', on_delete=django.db.models.deletion.DO_NOTHING, related_name='maquinista', to='practicaWebApp.Operario', verbose_name='Maquinista')),
                ('produccion', models.ManyToManyField(blank=True, db_column='produccion', related_name='produccion', to='practicaWebApp.Produccion', verbose_name='Producción')),
                ('setup', models.ManyToManyField(blank=True, db_column='setup', related_name='setup', to='practicaWebApp.Setup', verbose_name='RM AC AP')),
                ('supervisor', models.ForeignKey(db_column='supervisor', on_delete=django.db.models.deletion.DO_NOTHING, related_name='supervisor', to='practicaWebApp.Operario', verbose_name='Supervisor')),
            ],
            options={
                'verbose_name': 'Parte de impresión',
                'verbose_name_plural': 'Partes de impresión',
                'db_table': 'parte_impresion',
            },
        ),
    ]
